version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    volumes:
      - ./result:/app
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "db-data-at:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data-at:

networks:
  front-tier:
  back-tier: